name: Cloud Functions Deploy
'on': pull_request

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'api'
        runtime: 'nodejs18'
        env_vars: 'ENV=production,TASK_FIREBASE_SERVICE_ACCOUNT_KEY_FILE="${{ secrets.TASK_FIREBASE_SERVICE_ACCOUNT_KEY_FILE }}"'
        labels: 'enviroment=production,type=api'
