name: Tasks API Deploy into Cloud Functions Firebase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_LOCATION }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'api'
        runtime: 'nodejs18'
        source_dir: '.'
        project_id: ${{ secrets.PROJECT_ID }}
        labels: 'enviroment=production,type=api'
        env_vars: 'ENV=production,TASK_FIREBASE_SERVICE_ACCOUNT_KEY_FILE="${{ secrets.TASK_FIREBASE_SERVICE_ACCOUNT_KEY_FILE }}"'
